apiVersion: v1

baseDomain: qa.ecofeiras.com
credentialsMode: Manual

metadata:
  name: okd7711

compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform: {}  
    replicas: 0

controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
  platform: 
    aws:
      type: t3.2xlarge

platform:
  aws:
    region: us-east-1

publish: External

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzZiMjdhMjA5MzI1NDY4ZGEyNGNhNmU1ZmE4MGQwOTg6U0pYRDQ2R05MN0Y5VFAxN1lIMjBIM1RQRDJaMUNZVU5ZUUJHS0tJMzA2M0FROUU1RVc0QTFLUldNUTRFVVUwNQ==","email":"jufaerma@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzZiMjdhMjA5MzI1NDY4ZGEyNGNhNmU1ZmE4MGQwOTg6U0pYRDQ2R05MN0Y5VFAxN1lIMjBIM1RQRDJaMUNZVU5ZUUJHS0tJMzA2M0FROUU1RVc0QTFLUldNUTRFVVUwNQ==","email":"jufaerma@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWVlZDUyZjc1LTkyMGQtNDhjMy1iM2VhLTNkNGFlOTM2ODBjMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPR1V6TXpGa1pqRTNaRFkwTVRsa1lUSmpNMlk1TUdFeE1qQmlORFUzWVNKOS5aeS1RWk83TV9uV3daSHQ4STJpck5uMkFob0ZyU1g0SnBsc1lMcV92T2NDLWYyN1VscTN6NkhzN0xwN3dfWlQ2R05oaHZVc3R0eFk4aTd3eFlwNnZGcEJrelgxOFlFc01Mc3l6Wnl5TGl0YmYtU2E5VHZ6M1pmYnBSVmVGTXlxcVBpRnhLR21fNW10ZTd6dlBIcHRHYl9FQTlBbU5XMnpQQ3gtVE1rTTl6bGhwZ2NGcTF3NWhqdVlqRzN3alhqa0RoZjZ5Wmd5dUs1LWFKNzdwTGtnMVFBRG4xM2MxWHhRQ0xkVkNFSU1tTG55STlyZlNWX1FuSk1Lekp3MHdRbTBLdThRT2NHX2xMb0lfbW12MVZfSFQyX0NRTno0ZVp0VnM1UG80am0zUEtYblRodjVKanRBQ2tKbVdHdXlZUjU5YmJTMGx3al9UVHE0Z2ZCYkt1bWx5MDFaZnJnOXZaRHdCbWRjZ2wzT2F4Q2NuX3BlblZ2TnJTT3JqOXhheGN2VEs3dkg2OUFhenpkdEx6UTNfU0l4R1lzLWVlMkMyMl9EdTUwQXA2Y1dkY09XSzZTUDlqSERKRjV5SW1PeXRBY1NJem9nTFhHZFRSQ3BmZUJFWlZGVnNFbUZ2X29DV3ZQUFdGek5HdWRoRTdWY2FhX2RCT0o0c21MaTY5SkRieEtISUw1bHRQNlI2cGxWTGpma1N2WkRMNzFvVmo4bnhrMkxSVjcxbVBxUFhoRTFkaGgtdVBTM1FKeW02aWQ5SUdqMHZncDFFYnBrSXJuOTdxY1BSMFhaWFQ5WkdkQ19qdGlVbW5mcGVPQVdxOXpmcmlpWk5UZ2VJbU56aVdkVWNJLVBldWZaMHhNNkxwTFVZVlIwNG15UlBqZTNmNHlZUXpfLTB1V0dzMkJVdEtqWQ==","email":"jufaerma@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWVlZDUyZjc1LTkyMGQtNDhjMy1iM2VhLTNkNGFlOTM2ODBjMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPR1V6TXpGa1pqRTNaRFkwTVRsa1lUSmpNMlk1TUdFeE1qQmlORFUzWVNKOS5aeS1RWk83TV9uV3daSHQ4STJpck5uMkFob0ZyU1g0SnBsc1lMcV92T2NDLWYyN1VscTN6NkhzN0xwN3dfWlQ2R05oaHZVc3R0eFk4aTd3eFlwNnZGcEJrelgxOFlFc01Mc3l6Wnl5TGl0YmYtU2E5VHZ6M1pmYnBSVmVGTXlxcVBpRnhLR21fNW10ZTd6dlBIcHRHYl9FQTlBbU5XMnpQQ3gtVE1rTTl6bGhwZ2NGcTF3NWhqdVlqRzN3alhqa0RoZjZ5Wmd5dUs1LWFKNzdwTGtnMVFBRG4xM2MxWHhRQ0xkVkNFSU1tTG55STlyZlNWX1FuSk1Lekp3MHdRbTBLdThRT2NHX2xMb0lfbW12MVZfSFQyX0NRTno0ZVp0VnM1UG80am0zUEtYblRodjVKanRBQ2tKbVdHdXlZUjU5YmJTMGx3al9UVHE0Z2ZCYkt1bWx5MDFaZnJnOXZaRHdCbWRjZ2wzT2F4Q2NuX3BlblZ2TnJTT3JqOXhheGN2VEs3dkg2OUFhenpkdEx6UTNfU0l4R1lzLWVlMkMyMl9EdTUwQXA2Y1dkY09XSzZTUDlqSERKRjV5SW1PeXRBY1NJem9nTFhHZFRSQ3BmZUJFWlZGVnNFbUZ2X29DV3ZQUFdGek5HdWRoRTdWY2FhX2RCT0o0c21MaTY5SkRieEtISUw1bHRQNlI2cGxWTGpma1N2WkRMNzFvVmo4bnhrMkxSVjcxbVBxUFhoRTFkaGgtdVBTM1FKeW02aWQ5SUdqMHZncDFFYnBrSXJuOTdxY1BSMFhaWFQ5WkdkQ19qdGlVbW5mcGVPQVdxOXpmcmlpWk5UZ2VJbU56aVdkVWNJLVBldWZaMHhNNkxwTFVZVlIwNG15UlBqZTNmNHlZUXpfLTB1V0dzMkJVdEtqWQ==","email":"jufaerma@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqulxF0xj6CZe8fK6VqKhh+VcyhRHAOXsBdQkV5gqDvCMYL2iI+zR79HY6Pf0zn/6A+NXIzDu8VOngNnBOQSdN2zQu43Hz9Le1vRTztBfnhv2+TZYXmG2Cww43hJH46vIu4ccWRwS9GCzlnMUoIiQ3Sz2FVAtfkXT7+vG4sgsWSxkh8w9OaSXH71i+MMDZQfkKSKv48TMwFa8ztZi0MTsat28u1GVmy1KPkn/QyICLZ08EfXstrJx3rvFq5FNcTKMfvmaVZoeJSz9Wjw3zEwYQcBli0332vstEnquZg08Jbl9Poz6Gq5MQIkjw8Diq3NFi2o66aDmF4CuIkKEfIR60VFCfhbTv5ldhvttkcGCbxhWKuNhdQo7hwIICH1ihtp4xcOrwZHtCHo0mU/1L5II4SDziH4tEujcbGycgMt+oX4IuOaaatxfBdiU8MnmfT+omMsDQpZnRy12rcZFAhhw+9VhFN+nmrCDnLRgsdtT7rwtrepggrbFg2FeFs/pVU0s= faermanj@fedora
